import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
const target = resolve('.local/dist');
await mkdir(target, { recursive: true });
const result = spawnSync('npm', ['pack', '--pack-destination', target, '--json'], { env: { ...process.env, npm_config_cache: resolve('.local/npm-cache') }, encoding: 'utf8', shell: process.platform === 'win32' });
if (result.status !== 0) throw new Error(result.stderr || result.stdout);
const [packed] = JSON.parse(result.stdout);
const manifest = JSON.parse(await readFile('package.json', 'utf8'));
const forbidden = packed.files.filter(({ path }) => /(^|\/)(?:node_modules|\.local|\.env|\.npmrc|tests|reference|scripts)(\/|$)|\.map$|\.log$|\.tgz$/.test(path));
if (forbidden.length) throw new Error(`Unexpected packed files in ${manifest.name}: ${forbidden.map(f => f.path)}`);
const entry = { name: manifest.name, version: manifest.version, filename: packed.filename, integrity: packed.integrity, dependencies: manifest.dependencies ?? {}, files: packed.files.map(f => f.path) };
console.log(`${manifest.name}@${manifest.version}: ${packed.filename} (${packed.size} bytes)`);
await writeFile(resolve(target, 'manifest.json'), JSON.stringify([entry], null, 2) + '\n');
